/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * directly use fsrs::DEFAULT_PARAMETERS will cause error.
 * referencing statics in constants is unstable
 * see issue #119618 <https://github.com/rust-lang/rust/issues/119618> for more information
 * `static` and `const` variables can refer to other `const` variables. A `const` variable, however, cannot refer to a `static` variable.
 * to fix this, the value can be extracted to a `const` and then used.
 */
export const DEFAULT_PARAMETERS: number[]
export declare class FSRS {
  constructor()
  computeParameters(trainSet: Array<FSRSItem>): Array<number>
}
export declare class FSRSReview {
  constructor(rating: number, deltaT: number)
}
export declare class FSRSItem {
  constructor(reviews: Array<FSRSReview>)
  longTermReviewCnt(): number
}
